# Generated by Django 5.1.2 on 2024-12-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_profile1_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile1",
            name="account_age",
        ),
        migrations.AlterField(
            model_name="profile1",
            name="completed_recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="completed_by", to="project.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="profile1",
            name="saved_recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="saved_by", to="project.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="profile1",
            name="uploaded_recipes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="uploaded_by", to="project.recipe"
            ),
        ),
    ]
