# Generated by Django 5.1.2 on 2024-12-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_remove_profile1_saved_recipes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile1",
            name="completed_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="project.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="profile1",
            name="uploaded_recipes",
            field=models.ManyToManyField(
                blank=True, related_name="uploaded_by", to="project.recipe"
            ),
        ),
    ]
